---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
  
library(mmir)
```


```{r}

master <- mmir::attributes.fwmi %>% 
  select(final_id, beck_class, aspt, bibi_tv, bibi_ffg, bibi_habit) %>% 
  rename_all(tolower) %>% 
  mutate_if(is.character, tolower) %>% 
  distinct()
```

```{r}
data("onondaga")
```

```{r}
onon.df <- onondaga %>% 
  select(-phylum:-species) %>% 
  left_join(hier.df, by = "final_id")
onon.df <- onondaga
```

```{r}
fam.df <- onon.df %>% 
  select(unique_id, final_id, phylum:species) %>% 
  distinct() %>% 
  gather(rank, taxon, phylum:species) %>% 
  group_by(unique_id, final_id) %>% 
  mutate(rank = factor(rank, levels = c("phylum", "subphylum", "class", "subclass",
                                        "order", "suborder", "family", "subfamily",
                                        "tribe", "genus", "species")),
         taxon = if_else(taxon == "", as.character(NA), taxon)) %>% 
  fill(taxon) %>% 
  spread(rank, taxon)
test <- fam.df %>% 
  spread(rank, taxon)
```



```{r}
metrics.df <- onon.df %>% 
  select(unique_id) %>% 
  distinct() %>% 
  mutate(rich = taxa_rich(onon.df, unique_id, order, genus, taxon = NULL)),
         rich_ephem = taxa_rich(onon.df, unique_id, order, genus, taxon = "ephemeroptera"),
         pct_ephem = taxa_pct(onon.df, unique_id, count, order, "ephemeroptera"))
```

