library(usethis)
use_data(onondaga)
use_package("tidyr")
use_package("rlang", min_version = "0.4.4")
use_package("dplyr")
use_package("magrittr", min_version = "1.5")
use_package("knitr", type = "suggests")
use_package("DT", type = "suggests")
use_package("webshot", type = "suggests")
use_build_ignore("csv")
use_build_ignore("imports.R")
use_build_ignore("icons")
use_pipe(export = TRUE)
use_gpl3_license()
use_readme_rmd()
use_cran_badge()
use_lifecycle_badge("maturing")
use_binder_badge()
use_travis(browse = interactive(), ext = c("org", "com"))
# use_tidy_release_test_e
options(usethis.full_name = "Zachary M. Smith")
edit_r_profile()

use_logo("icons/mmir_hex-sticker.png")

use_tidy_ci()
use_tidy_description()
use_tidy_eval()
use_tidy_versions()
use_tidy_github()
use_tidy_style()
